/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'APIConnectionSettings': {
		'en': 'API connection settings',
		'de': 'API-Verbindungseinstellungen',
		'ru': 'Настройки подключения API',
		'pt': 'Configurações de conexão API',
		'nl': 'Instellingen voor API-verbinding',
		'fr': 'Paramètres de connexion API',
		'it': 'Impostazioni di connessione API',
		'es': 'Configuración de conexión API',
		'pl': 'Ustawienia połączenia API',
		'zh-cn': 'API 连接设置'
	},
	'gatewayIP': {
		'en': 'gateway IP',
		'de': 'Gateway-IP',
		'ru': 'IP шлюза',
		'pt': 'IP do gateway',
		'nl': 'Gateway IP',
		'fr': 'IP de la passerelle',
		'it': 'IP del gateway',
		'es': 'IP de acceso',
		'pl': 'IP bramy',
		'zh-cn': '网关IP'
	},
	'gatewayIPHint': {
		'en': 'e.g. 192.168.1.150',
		'de': 'z.B. 192.168.1.150',
		'ru': 'например 192.168.1.150',
		'pt': 'e.g. 192.168.1.150',
		'nl': 'bijvoorbeeld 192.168.1.150',
		'fr': 'par exemple, 192.168.1.150',
		'it': 'ad esempio, 192.168.1.150',
		'es': 'por ejemplo, 192.168.1.150',
		'pl': 'na przykład 192.168.1.150',
		'zh-cn': '例如192.168.1.150'
	},
	'username': {
		'en': 'username',
		'de': 'Nutzername',
		'ru': 'имя пользователя',
		'pt': 'nome do usuário',
		'nl': 'gebruikersnaam',
		'fr': 'Nom d\'utilisateur',
		'it': 'nome utente',
		'es': 'nombre de usuario',
		'pl': 'Nazwa Użytkownika',
		'zh-cn': '用户名'
	},
	'usernameHint': {
		'en': 'e.g. admin',
		'de': 'z.B. admin',
		'ru': 'например админ',
		'pt': 'por exemplo. admin',
		'nl': 'bijv. beheerder',
		'fr': 'par exemple. admin',
		'it': 'per esempio. ammin',
		'es': 'p.ej. admin',
		'pl': 'np. admin',
		'zh-cn': '例如行政'
	},
	'AuthToken': {
		'en': 'Authentification token',
		'de': 'Authentifizierungstoken',
		'ru': 'Токен аутентификации',
		'pt': 'Token de autenticação',
		'nl': 'authenticatie token',
		'fr': 'Jeton d\'authentification',
		'it': 'Token di autenticazione',
		'es': 'Token de autenticación',
		'pl': 'Token uwierzytelniający',
		'zh-cn': '认证令牌'
	},
	'AuthTokenHint': {
		'en': 'Authentification token for your Wiser by Feller RESTFul API.<br>As soon you start the request the physical buttons of the Wiser-uGateway will start flashing for 30 seconds. For a valid request, one of the physical buttons has to be pressed within 30 seconds!',
		'de': 'Authentifizierungstoken für Ihr Wiser by Feller RESTFul API.<br> Sobald Sie die Anfrage starten, blinken die physischen Tasten des Wiser-uGateway für 30 Sekunden. Für eine gültige Anfrage muss innerhalb von 30 Sekunden eine der physischen Tasten gedrückt werden!',
		'ru': 'Токен аутентификации для вашего Wiser by Feller RESTFul API.<br> Как только вы начнете запрос, физические кнопки Wiser-uGateway начнут мигать в течение 30 секунд. Для правильного запроса одна из физических кнопок должна быть нажата в течение 30 секунд!',
		'pt': 'Token de autenticação para seu Wiser by Feller RESTFul API.<br> Assim que você iniciar a solicitação, os botões físicos do Wiser-uGateway começarão a piscar por 30 segundos. Para uma solicitação válida, um dos botões físicos deve ser pressionado em 30 segundos!',
		'nl': 'Verificatietoken voor uw Wiser by Feller RESTFul API.<br> Zodra je het verzoek start, gaan de fysieke knoppen van de Wiser-uGateway 30 seconden knipperen. Voor een geldig verzoek moet binnen 30 seconden een van de fysieke knoppen worden ingedrukt!',
		'fr': 'Jeton d\'authentification pour votre API RESTFul Wiser by Feller.<br> Dès que vous lancez la demande, les boutons physiques de la Wiser-uGateway se mettent à clignoter pendant 30 secondes. Pour une demande valide, un des boutons physiques doit être pressé dans les 30 secondes !',
		'it': 'Token di autenticazione per Wiser by Feller RESTFul API.<br> Non appena si avvia la richiesta i pulsanti fisici del Wiser-uGateway inizieranno a lampeggiare per 30 secondi. Per una richiesta valida, uno dei pulsanti fisici deve essere premuto entro 30 secondi!',
		'es': 'Token de autenticación para su API RESTFul de Wiser by Feller.<br> Tan pronto como inicie la solicitud, los botones físicos de Wiser-uGateway comenzarán a parpadear durante 30 segundos. Para una solicitud válida, ¡uno de los botones físicos debe presionarse en 30 segundos!',
		'pl': 'Token uwierzytelniający dla Twojego Wiser by Feller RESTFul API.<br> Natychmiast po uruchomieniu żądania fizyczne przyciski Wiser-uGateway zaczną migać przez 30 sekund. Aby żądanie było prawidłowe, jeden z fizycznych przycisków musi zostać wciśnięty w ciągu 30 sekund!',
		'zh-cn': 'Feller RESTFul API 的 Wiser 身份验证令牌.<br>一旦您开始请求，Wiser-uGateway 的物理按钮将开始闪烁 30 秒。对于有效请求，必须在 30 秒内按下其中一个物理按钮！'
	},
	'ButtonGetAuthToken': {
		'en': 'Obtain authentification token',
		'de': 'Authentifizierungstoken erhalten',
		'ru': 'Получить токен аутентификации',
		'pt': 'Obtenha o token de autenticação',
		'nl': 'Verkrijg authenticatietoken',
		'fr': 'Obtenir un jeton d\'authentification',
		'it': 'Ottieni token di autenticazione',
		'es': 'Obtener el token de autenticación',
		'pl': 'Uzyskaj token uwierzytelniający',
		'zh-cn': '获取认证令牌'
	},
	'SuccessGetAuthToken': {
		'en': 'Authentification token usccessfully obtained!',
		'de': 'Authentifizierungstoken erfolgreich erhalten!',
		'ru': 'Токен аутентификации получен успешно!',
		'pt': 'Token de autenticação obtido com sucesso!',
		'nl': 'Authenticatie token succesvol verkregen!',
		'fr': 'Jeton d\'authentification obtenu avec succès !',
		'it': 'Token di autenticazione ottenuto con successo!',
		'es': '¡Token de autenticación obtenido con éxito!',
		'pl': 'Pomyślnie uzyskano token uwierzytelniający!',
		'zh-cn': '认证令牌成功获取！'
	},
	'error': {
		'en': 'error',
		'de': 'Error',
		'ru': 'ошибка',
		'pt': 'erro',
		'nl': 'fout',
		'fr': 'Erreur',
		'it': 'errore',
		'es': 'error',
		'pl': 'błąd',
		'zh-cn': '错误'
	},
	'ErrorGetAuthTokenTitle': {
		'en': 'Error while obtaining',
		'de': 'Fehler beim Abrufen',
		'ru': 'Ошибка при получении',
		'pt': 'Erro ao obter',
		'nl': 'Fout tijdens het verkrijgen',
		'fr': 'Erreur lors de l\'obtention',
		'it': 'Errore durante l\'ottenimento',
		'es': 'Error al obtener',
		'pl': 'Błąd podczas uzyskiwania',
		'zh-cn': '获取时出错'
	},
	'ObtainAuthTokenWait': {
		'en': 'Obtaining authentification token, please wait...',
		'de': 'Authentifizierungstoken wird abgerufen, bitte warten...',
		'ru': 'Получение токена аутентификации, подождите ...',
		'pt': 'Obtendo token de autenticação, aguarde ...',
		'nl': 'Verkrijgen van authenticatietoken, even geduld a.u.b...',
		'fr': 'Obtention du jeton d\'authentification, veuillez patienter...',
		'it': 'Ottenimento del token di autenticazione, attendere prego...',
		'es': 'Obteniendo el token de autenticación, espere ...',
		'pl': 'Pobieranie tokena uwierzytelniania, proszę czekać...',
		'zh-cn': '正在获取认证令牌，请稍候...'
	},
	'AdapterNotAlive': {
		'en': 'Adapter must be running!',
		'de': 'Adapter muss laufen!',
		'ru': 'Адаптер должен быть запущен!',
		'pt': 'O adaptador deve estar em execução!',
		'nl': 'Adapter moet draaien!',
		'fr': 'L\'adaptateur doit fonctionner!',
		'it': 'L\'adattatore deve essere in esecuzione!',
		'es': '¡El adaptador debe estar funcionando!',
		'pl': 'Adapter musi być uruchomiony!',
		'zh-cn': '适配器必须正在运行！'
	},
	'AdapterStateTitle': {
		'en': 'Adapter state',
		'de': 'Adapterstatus',
		'ru': 'Состояние адаптера',
		'pt': 'Estado do adaptador',
		'nl': 'Adapterstatus:',
		'fr': 'État de l\'adaptateur',
		'it': 'Stato dell\'adattatore',
		'es': 'Estado del adaptador',
		'pl': 'Stan adaptera',
		'zh-cn': '适配器状态'
	},
	'on save adapter restarts with new config immediately': {
		'en': 'on save adapter restarts with new config immediately',
		'de': 'Beim Speichern der Einstellungen wird der Adapter sofort neu gestartet.',
		'ru': 'сохранить адаптера перезагрузки с новый конфиг сразу',
		'pt': 'em salvar adaptador reinicia com nova configuração e imediatamente',
		'nl': 'op bespaar adapter opnieuw met nieuwe config onmiddellijk',
		'fr': 'sur enregistrer l\'adaptateur redémarre avec la nouvelle configuration, immédiatement',
		'it': 'salva adattatore riavvia con la nuova config immediatamente',
		'es': 'en guardar adaptador se reinicia con la nueva config de inmediato',
		'pl': 'zapisz ponownym uruchomieniu zasilacza z nowy konfig raz',
		'zh-cn': '在保存适配器重新启动与新的配置立即'
	}
};